USE sakshamshop;


-- View All Tables Data

SELECT * FROM customers;

SELECT * FROM products;

SELECT * FROM orders;

SELECT * FROM order_items;

SELECT * FROM payments;



-- Total Revenue

SELECT 
    SUM(amount) AS total_revenue
FROM payments;



-- Revenue Generated By Each Product

SELECT 
    p.product_name,
    SUM(oi.quantity * p.price) AS revenue
FROM order_items oi
JOIN products p 
    ON oi.product_id = p.product_id
JOIN orders o 
    ON oi.order_id = o.order_id
WHERE o.order_status = 'Delivered'
GROUP BY p.product_name
ORDER BY revenue DESC;



-- Count Cancelled Orders

SELECT 
    COUNT(*) AS cancelled_orders
FROM orders
WHERE order_status = 'Cancelled';



-- Count Orders By Status

SELECT 
    order_status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_status;



-- Sales By Category

SELECT
    p.category,
    SUM(oi.quantity * p.price) AS total_sales
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'Delivered'
GROUP BY p.category
ORDER BY total_sales DESC;



-- Customer Order Summary

SELECT
    c.name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.name
ORDER BY total_orders DESC;



-- Payment Mode Analysis

SELECT
    payment_mode,
    SUM(amount) AS total_amount
FROM payments
GROUP BY payment_mode
ORDER BY total_amount DESC;
